version: '3.7'
services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    env_file:
      - .env
    expose:
      - "3306"
    restart: on-failure
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress/.
    expose:
      - "9000"
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx/.
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
    driver_opts:
      type: none
      device: /home/amahla/data/mariadb
      o: bind
  wordpress_data:
    driver_opts:
      type: none
      device: /home/amahla/data/wordpress
      o: bind

networks:
  inception:
    name: inception
