version: '3.7'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    expose:
      - "3306"
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
#      - /home/amahla/data/mariadb:/var/lib/mysql
    networks:
      - inception
#  wordpress:
#    depends_on:
#      - mariadb
#    container_name: wordpress
#    build: ./requirements/wordpress/.
#    expose:
#      - "9000"
#    restart: always
#    volumes:
#      - wordpress_data:/var/www/worldpress
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    restart: always
    networks:
      - inception

volumes:
  mariadb_data:
    driver_opts:
      type: volume
      source: /home/amahla/data/mariadb
      o: bind

#  /home/amahla/data/mariadb
#  /home/amahla/data/wordpress:

networks:
  inception:
    name: inception
