version: '3.7'
services:

  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: requirements/mariadb/.
    image:  mariadb
    expose:
      - "3306"
    restart:  unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mysql $DB_NAME -uroot -p$DB_ROOT_PWD -e 'SELECT 1' || exit 1"]
      interval: 0.5s
      retries: 100

  redis:
    container_name: redis
    build: requirements/bonus/redis/.
    image:  redis
    expose:
      - "6379"
    restart:  unless-stopped
    networks:
      - inception


  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    container_name: wordpress
    image:  wordpress
    env_file:
      - .env
    build: requirements/wordpress/.
    expose:
      - "9000"
    restart:  unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx/.
    image:  nginx
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
    driver_opts:
      type: none
      device: /home/amahla/data/mariadb
      o: bind
  wordpress_data:
    driver_opts:
      type: none
      device: /home/amahla/data/wordpress
      o: bind

networks:
  inception:
    name: inception
